objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_CNPJ__c</fullName>
        <externalId>true</externalId>
        <label>CNPJ</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_CPF__c</fullName>
        <externalId>true</externalId>
        <label>CPF</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Fidelidade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fidelidade</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Esse cliente já possui registro de Fidelidade criado. Não é possível criar um novo registro.</errorMessage>
            <filterItems>
                <field>TW1_Fidelidade__c.TW1_Nome_Cliente__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TW1_Fidelidade__c</referenceTo>
        <relationshipLabel>Cliente</relationshipLabel>
        <relationshipName>TW1_Relation_Fidelidade_Cliente</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Contas (Shopping)</relationshipLabel>
        <relationshipName>Contas1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ativa</fullName>
                </value>
                <value>
                    <fullName>Inativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    
    
    
    
    
    

</CustomObject>

objects/TW1_Fidelidade__c.object
<CustomObject>
    
    
    
    
    <fields>
        <fullName>TW1_Modalidade__c</fullName>
        <label>Modalidade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <default>true</default>
                    <label>Prospect</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    
    
    
    
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Fidelidade</relationshipLabel>
        <relationshipName>Fidelidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fidelidade</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número Fidelidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fidelidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    
</CustomObject>

objects/TW1_Historico__c.object
<CustomObject>
    
    
    <label>Histórico</label>
    <nameField>
        <displayFormat>HIST-{00000000}</displayFormat>
        <label>Código Histórico</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos</pluralLabel>
    
    
</CustomObject>

objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>TW1_SGL_Empreendimento__c</fullName>
        <externalId>true</externalId>
        <label>SGL Empreendimento</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TR_ExpirarNota_Sch_Test.cls
@istest
public  with sharing class TR_ExpirarNota_Sch_Test {
    
    @isTest static void TestExpiraNotaJob() { 
        
        recordtype varecodtype=[select id,name from recordtype where name='Conta pessoal padrão' limit 1];
        
        Anc_Utils_cls.LogToSystemDebug('Criando conta');
        Account act = new Account(); 
        act.FirstName ='Teste';
        act.LastName ='silva';
        act.TW1_CPF__c='74745710569';
        act.TW1_CNPJ__c='27364928000101';
        act.Phone = '2133337444';
        act.PersonMobilePhone = '21999984578';
        act.RecordTypeId = varecodtype.id;
        insert act;
        Anc_Utils_cls.LogToSystemDebug('conta criada ' + act);
        
        Anc_Utils_cls.LogToSystemDebug('Criando fidelidade');
        TW1_Fidelidade__c vafidelidade = new TW1_Fidelidade__c();
        vafidelidade.TW1_Modalidade__c='Prospect';
        vafidelidade.TW1_Nome_Cliente__c=act.id;
        insert vafidelidade;       
        Anc_Utils_cls.LogToSystemDebug('Fidelidade criada ' + vafidelidade);
        
        TW1_Shopping__c shopping = new TW1_Shopping__c();
        shopping.TW1_SGL_Empreendimento__c = 'RDB';
        shopping.Name = 'Rio Design Barra';
        
        Insert shopping;
        
        recordtype rtAcc = [Select Id,Name From recordtype where Name='Loja' Limit 1];
        Anc_Utils_cls.LogToSystemDebug('Criando Loja');
        Account accLoja = new Account();
        accLoja.Name = 'Loja Americanas';
        accLoja.RecordTypeId = rtAcc.Id;
        accLoja.TW1_Shopping__c = shopping.Id;
        Insert accLoja;
        Anc_Utils_cls.LogToSystemDebug('Loja criada ' + accLoja);
        
        Anc_Utils_cls.LogToSystemDebug('Criando Historico');
        TW1_Historico__c historico = new TW1_Historico__c();
        historico.TW1_Fidelidade__c = vafidelidade.Id;
        historico.TW1_Loja__c = accLoja.Id;
        historico.TW1_Status__c = 'Válida';
        historico.TW1_Data_da_Nota__c = Date.today().addDays(-95);
        historico.TW1_Valor_RS__c = 120;
        insert historico;
        Anc_Utils_cls.LogToSystemDebug('Historico criado ' + historico);
        
        Test.startTest();  
        Anc_ScheaduleUtils_cls.scheadule('TR_ExpirarNota_SCH', DateTime.now().addMinutes(1)); 
        Test.stopTest(); 
    } 
}