objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_Celular__c</fullName>
        <label>Celular</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>TW1_Estado__c</fullName>
        <label>Estado</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Estado_civil__c</fullName>
        <label>Estado civil</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solteiro(a)</fullName>
                </value>
                <value>
                    <fullName>Casado(a)</fullName>
                </value>
                <value>
                    <fullName>Viúvo(a)</fullName>
                </value>
                <value>
                    <fullName>Divorciado(a)</fullName>
                </value>
                <value>
                    <fullName>União estável</fullName>
                </value>
                <value>
                    <fullName>Outros</fullName>
                    <isActive>false</isActive>
                    <label>Outros</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Identidade__c</fullName>
        <label>Identidade</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Inscricao_Municipal__c</fullName>
        <label>Inscrição Municipal</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Inscricao_estadual__c</fullName>
        <label>Inscrição estadual</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Naturalidade__c</fullName>
        <label>Naturalidade</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_fantasia__c</fullName>
        <label>Nome Fantasia</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Sexo__c</fullName>
        <label>Sexo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Masculino</fullName>
                </value>
                <value>
                    <fullName>Feminino</fullName>
                </value>
                <value>
                    <fullName>Indefinido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    
    
    
    
    
    

</CustomObject>

objects/Tw1_Dados_de_Contato_adicionais__c.object
<CustomObject>
    <description>Objeto para armazenar dados de contato das contas e contatos, como: telefone, e-mail, etc</description>
    <fields>
        <fullName>Tw1_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Dados_de_Contatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tw1_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Dados_de_Contatos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tw1_Contato__c</fullName>
        <label>Contato</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Dados de Contato Adicionais</label>
    <nameField>
        <displayFormat>DC# {00000000}</displayFormat>
        <label>Dados de Contato Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dados de Contatos Adicionais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Naturalidade__c.object
<CustomObject>
    <label>Naturalidade</label>
    <nameField>
        <label>Nome de Naturalidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Naturalidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Projurid__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Conta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ações - Projurid</relationshipLabel>
        <relationshipName>TW1_Projurid_Conta</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Processo__c</fullName>
        <externalId>true</externalId>
        <label>Número do Processo</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Projurid</label>
    <nameField>
        <displayFormat>A-{YYYY}{MM}-{0000}</displayFormat>
        <label>Projurid</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projurid</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Cal_Servico_Repo_AggregatePessoa.cls
public class Cal_Servico_Repo_AggregatePessoa {
	
   public Account GetAccountById(string accountId)
   {
   		List<Account> contas = [SELECT id,
            Tw1_Codigo_Cliente_UAU__c,
            Name,
            Tw1_N_Documento__c,
            Tw1_E_mail__c,
            Tw1_E_mail_Alternativo__c,
            Tw1_Celular__c,
            Tw1_Data_de_Nascimento__c,
            recordtype.Name,
            BillingStreet,
            TW1_Complemento_Endereco_Cobranca__c,	
            BillingCity,
            BillingState,
            BillingPostalCode,
            BillingCountry,
            Tw1_CEP__c,
			Tw1_Estado__c,
            Tw1_Identidade__c,
            Tw1_Profissao__c,
            Tw1_Sexo__c,
            Tw1_Estado_Civil__c,
            Tw1_Naturalidade__c,
            Tw1_Nome_Fantasia__c,
            Tw1_Inscricao_Municipal__c,
            Tw1_Inscricao_Estadual__c,
            ShippingStreet,
            ShippingState,
            ShippingCity,
            ShippingPostalCode,
            TW1_Nacionalidade_st__c,
            TW1_Profissao_UAU__c
            FROM Account where Id = :accountId];
       
        if(contas.size() < 1)
            return null;
        else
            return contas[0];
   } 
   
   public Account GetAccountByCodigoUau(string codigoUau)
   {
   		List<Account> contas = [SELECT id,
            Tw1_Codigo_Cliente_UAU__c,
            Name,
            Tw1_N_Documento__c,
            Tw1_E_mail__c,
            Tw1_E_mail_Alternativo__c,
            Tw1_Celular__c,
            Tw1_Data_de_Nascimento__c,
            recordtype.Name,
            BillingStreet,
            TW1_Complemento_Endereco_Cobranca__c,	
            BillingCity,
            BillingState,
            BillingPostalCode,
            BillingCountry,
            Tw1_CEP__c,
			Tw1_Estado__c,
            Tw1_Identidade__c,
            Tw1_Profissao__c,
            Tw1_Sexo__c,
            Tw1_Estado_Civil__c,
            Tw1_Naturalidade__c,
            Tw1_Nome_Fantasia__c,
            Tw1_Inscricao_Municipal__c,
            Tw1_Inscricao_Estadual__c,
            ShippingStreet,
            ShippingState,
            ShippingCity,
            ShippingPostalCode,
            TW1_Nacionalidade_st__c,
            TW1_Profissao_UAU__c
            FROM Account where Tw1_Codigo_Cliente_UAU__c = :codigoUau];
       
        if(contas.size() < 1)
            return null;
        else
            return contas[0];
   } 
    
   public List<Tw1_Dados_de_Contato_adicionais__c> GetContatosAdcionais(ID AccountId)
   {
       return [SELECT 
               id, 
               Tw1_Account__c, 
               Tw1_Contact__c,
               recordtype.name, 
               Tw1_Contato__c 
               FROM Tw1_Dados_de_Contato_adicionais__c
               WHERE Tw1_Account__c = :AccountId];
   }
    
   public Account GetAccountByCPF(string cpf)
   {
   		List<Account> contas = [
            SELECT id,
            Tw1_Codigo_Cliente_UAU__c,
            Name,
            Tw1_N_Documento__c,
            Tw1_E_mail__c,
            Tw1_E_mail_Alternativo__c,
            Tw1_Celular__c,
            Tw1_Data_de_Nascimento__c,
            recordtype.Name,
            BillingStreet,
            TW1_Complemento_Endereco_Cobranca__c,	
            BillingCity,
            BillingState,
            BillingPostalCode,
            BillingCountry,
            Tw1_CEP__c,
			Tw1_Estado__c,
            Tw1_Identidade__c,
            Tw1_Profissao__c,
            Tw1_Sexo__c,
            Tw1_Estado_Civil__c,
            Tw1_Naturalidade__c,
            Tw1_Nome_Fantasia__c,
            Tw1_Inscricao_Municipal__c,
            Tw1_Inscricao_Estadual__c,
            ShippingStreet,
            ShippingState,
            ShippingCity,
            ShippingPostalCode,
            TW1_Nacionalidade_st__c         
            FROM Account 
            where Tw1_N_Documento__c = :cpf];
        if(contas.size() < 1)
            return null;
        else
            return contas[0];
   } 
    
    public List<Account> GetListaClientesNaoAtualizadosEmPeriodoDias(integer tempoNaoAtualizado)
    {
        return [SELECT id FROM Account Where LastModifiedDate >= :DateTime.now().addDays(-tempoNaoAtualizado) LIMIT 1000];
    }
    
    public void Modify(Account pessoa)
    {
        update pessoa;
    }
    
    public TW1_Projurid__c GetProcessoPorNumeroEConta(Id accountId, string numeroProcesso)
    {
        List<TW1_Projurid__c> retorno = [SELECT id FROM TW1_Projurid__c WHERE TW1_Conta__c =:accountId AND TW1_Numero_Processo__c = :numeroProcesso];
   		
        if(retorno.size() < 1)
            return null;
        else
            return retorno[0];
    }
    
    public void IncluirProcessos(List<TW1_Projurid__c> listaProcessos)
    {
        UpSert listaProcessos;
    }
    
    public RecordType GetRecordTypePessoaFisica()
    {
        return [Select Id,Name FROM RecordType Where name = 'Pessoa Fisica'];
    }
    
    public RecordType GetRecordTypePessoaJuridica()
    {
        return [Select Id,Name FROM RecordType Where name = 'Pessoa Jurídica'];
    }
    
    public RecordType GetTipoContatoAdcionalByTipoTelefoneUAU(string tipoTelefoneUAU)
    {
        if(tipoTelefoneUAU == '0')
            return [Select Id,Name FROM RecordType Where name = 'Telefone'];
        else if(tipoTelefoneUAU == '1')
        	return [Select Id,Name FROM RecordType Where name = 'Comercial'];
        else if(tipoTelefoneUAU == '2')
            return [Select Id,Name FROM RecordType Where name = 'Celular'];
        else if(tipoTelefoneUAU == '4')
            return [Select Id,Name FROM RecordType Where name = 'Fax'];
        
        throw new Cal_Cls_Infra_Exception('Não foi encontrado o tipo de telefone com o tipo do UAU ' + tipoTelefoneUAU);
    }
    
    public List<Tw1_Dados_de_Contato_adicionais__c> GetContatoAdcioinaisByAccountID(string AccountId)
    {
        return [SELECT id FROM Tw1_Dados_de_Contato_adicionais__c WHERE Tw1_Account__c =:AccountId];
    }
}