objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_Email__c</fullName>
        <label>E-mail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>TW1_Sexo__c</fullName>
        <label>Sexo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Masculino</fullName>
                </value>
                <value>
                    <fullName>Feminino</fullName>
                </value>
                <value>
                    <fullName>Indefinido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Contas (Shopping)</relationshipLabel>
        <relationshipName>Contas1</relationshipName>
        <type>Lookup</type>
    </fields>
    
    
    
    
    
    

</CustomObject>

objects/TW1_Caixa__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Operador__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Operador</label>
        <referenceTo>TW1_Operador__c</referenceTo>
        <relationshipLabel>Caixas</relationshipLabel>
        <relationshipName>Caixas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Caixa</label>
    <nameField>
        <label>Nome de Caixa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Caixas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TW1_Empresa__c.object
<CustomObject>
    <label>Empresa</label>
    <nameField>
        <label>Razão Social</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Operador__c.object
<CustomObject>

    <fields>
        <fullName>TW1_Email__c</fullName>
        <externalId>true</externalId>
        <label>E-mail</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Empresa__c</fullName>
        <label>Empresa</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_do_Usuario__c</fullName>
        <label>Nome do Usuário</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Senha__c</fullName>
        <externalId>true</externalId>
        <label>Senha</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Operadores</relationshipLabel>
        <relationshipName>Operadores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Operador</fullName>
                </value>
                <value>
                    <fullName>Coordenador</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Operador</label>
    <nameField>
        <label>Nome do Operador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operadores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Parametros_Promocao__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Acumula_Saldo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Acumula Saldo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Concurso_Cultural__c</fullName>
        <label>Concurso Cultural</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sim</fullName>
                </value>
                <value>
                    <fullName>Não</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Contabiliza_Bonus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Considerar condição especial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Formas_de_Pagamento__c</fullName>
        <label>Formas de Pagamento</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dinheiro</fullName>
                </value>
                <value>
                    <fullName>Cartão Debito</fullName>
                    <label>Cartão Débito</label>
                </value>
                <value>
                    <fullName>Cartão Caixa</fullName>
                </value>
                <value>
                    <fullName>Cartão Caixa ELO</fullName>
                </value>
                <value>
                    <fullName>Visa Vale</fullName>
                </value>
                <value>
                    <fullName>Visa Platinum</fullName>
                </value>
                <value>
                    <fullName>Visa Infinite</fullName>
                </value>
                <value>
                    <fullName>Clube Rio Design</fullName>
                </value>
                <value>
                    <fullName>Dinheiro(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Débito(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Crédito(FDS)</fullName>
                </value>
                <value>
                    <fullName>Aplicativo</fullName>
                </value>
                <value>
                    <fullName>Aplicativo(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Crédito</fullName>
                </value>
                <value>
                    <fullName>CLUBE RDB</fullName>
                    <isActive>false</isActive>
                    <label>CLUBE RDB</label>
                </value>
                <value>
                    <fullName>Cartão Credito</fullName>
                    <isActive>false</isActive>
                    <label>Cartão Credito</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipName>Promo_es</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Troca_por__c</fullName>
        <label>Troca por</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Brinde</fullName>
                </value>
                <value>
                    <fullName>Cupom</fullName>
                </value>
                <value>
                    <fullName>Ambos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parâmetros da Promoção</label>
    <nameField>
        <label>Nome da Promoção</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parâmetros da Promoções</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TW1_Shopping__c.object
<CustomObject>
    <fields>
        <fullName>TW1_SGL_Empreendimento__c</fullName>
        <externalId>true</externalId>
        <label>SGL Empreendimento</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TW1_Ancar_CordenadorManager_tst.cls
@isTest
private class TW1_Ancar_CordenadorManager_tst {

    static testMethod void testdoCoordenadorShopping() {
         // setup test data  
       	
        Account acc = new Account();
        acc.TW1_Sexo__c ='Masculino';
        acc.Phone ='998837329';
        acc.LastName ='Caruzo';
        acc.PersonEmail = 'jjxxxaaa@gmaisl.com';
        
        Insert acc;
         
          
         
        TW1_Shopping__c shopping = new TW1_Shopping__c();
    		shopping.TW1_SGL_Empreendimento__c = 'BPS';
        	shopping.Name = 'Barra Shopping';
        
         Insert shopping;
        
        
     TW1_Operador__c operador  = new TW1_Operador__c();
    	operador.Name = 'Leonardo';
    	operador.TW1_Email__c = 'leonardo@gmail.com';
    	operador.TW1_Empresa__c = 'Triscal';
        operador.TW1_Senha__c = '123456';
    	operador.TW1_Nome_do_Usuario__c = 'leo';
    	operador.TW1_Shopping__c = shopping.Id; 
    	operador.TW1_Tipo__c = 'Coordenador';
    
    Insert operador;
    
      TW1_Parametros_Promocao__c promocao = new TW1_Parametros_Promocao__c();
    	promocao.Name = 'Promo Teste Tabajara';
    	promocao.TW1_Troca_por__c = 'Brinde';
    	promocao.TW1_Acumula_Saldo__c = true;
    	promocao.TW1_Contabiliza_Bonus__c = true;
    	promocao.TW1_Formas_de_Pagamento__c = 'Dinheiro';
    	promocao.TW1_Concurso_Cultural__c = 'Sim';
        promocao.TW1_Shopping__c = shopping.Id;
        promocao.TW1_Data_Fim__c = DateTime.now().date();
    
    Insert promocao;
    
           
       TW1_Caixa__c vaCaixa = new TW1_Caixa__c();
        vaCaixa.Name = 'Caixa Marcao';
    	vaCaixa.TW1_Operador__c = operador.Id;
        vaCaixa.CreatedDate = DateTime.now().date();

       Insert vaCaixa;        
        
        // COMEÇA O TESTE
        string nome= '';
        string Cpf = '';
        
        //+'&nome='+Nome+'&cpf='+Cpf

        RestRequest request = new RestRequest();
        request.requestUri ='/services/apexrest/Cordenador';
        
        //request.addParameter('Id', acc.Id);
        //request.addParameter('IdPromocao', promocao.Id);
        
        request.addParameter('IdShopping', shopping.Id);
        //request.addParameter('IdOperador', operador.Id);
        //request.addParameter('SenhaOperaodor', operador.TW1_Senha__c);

        request.httpMethod = 'GET';
		
        RestContext.request = request;
         System.debug(RestContext.request);
        
        CordenadorManager.getCordenadorPorShopping();

    }
    
    static testMethod void testdoCoordenadorId() {
         // setup test data  
       	
        Account acc = new Account();
        acc.TW1_Sexo__c ='Masculino';
        acc.Phone ='998837329';
        acc.LastName ='Caruzo';
        acc.PersonEmail = 'jjxxxaaa@gmaisl.com';
        
        Insert acc;
         
          
         
        TW1_Shopping__c shopping = new TW1_Shopping__c();
    		shopping.TW1_SGL_Empreendimento__c = 'BPS';
        	shopping.Name = 'Barra Shopping';
        
         Insert shopping;
        
        
     TW1_Operador__c operador  = new TW1_Operador__c();
    	operador.Name = 'Leonardo';
    	operador.TW1_Email__c = 'leonardo@gmail.com';
    	operador.TW1_Empresa__c = 'Triscal';
        operador.TW1_Senha__c = '123456';
    	operador.TW1_Nome_do_Usuario__c = 'leo';
    	operador.TW1_Shopping__c = shopping.Id; 
    	operador.TW1_Tipo__c = 'Coordenador';
    
    Insert operador;
    
      TW1_Parametros_Promocao__c promocao = new TW1_Parametros_Promocao__c();
    	promocao.Name = 'Promo Teste Tabajara';
    	promocao.TW1_Troca_por__c = 'Brinde';
    	promocao.TW1_Acumula_Saldo__c = true;
    	promocao.TW1_Contabiliza_Bonus__c = true;
    	promocao.TW1_Formas_de_Pagamento__c = 'Dinheiro';
    	promocao.TW1_Concurso_Cultural__c = 'Sim';
        promocao.TW1_Shopping__c = shopping.Id;
        promocao.TW1_Data_Fim__c = DateTime.now().date();
    
    Insert promocao;
    
           
       TW1_Caixa__c vaCaixa = new TW1_Caixa__c();
        vaCaixa.Name = 'Caixa Marcao';
    	vaCaixa.TW1_Operador__c = operador.Id;
        vaCaixa.CreatedDate = DateTime.now().date();

       Insert vaCaixa;        
        
        // COMEÇA O TESTE
        string nome= '';
        string Cpf = '';
        
        //+'&nome='+Nome+'&cpf='+Cpf

        RestRequest request = new RestRequest();
        request.requestUri ='/services/apexrest/Cordenador';
        
        //request.addParameter('Id', acc.Id);
        //request.addParameter('IdPromocao', promocao.Id);
        
        //request.addParameter('IdShopping', shopping.Id);
        request.addParameter('IdOperador', operador.Id);
        request.addParameter('SenhaOperaodor', operador.TW1_Senha__c);

        request.httpMethod = 'GET';
		
        RestContext.request = request;
         System.debug(RestContext.request);
        
         CordenadorManager.getCordenadorPorShopping();

    }
}