objects/Account.object
<CustomObject>
    <fields>
        <fullName>TW1_CPF__c</fullName>
        <externalId>true</externalId>
        <label>CPF</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    
    
    
    
    
    

</CustomObject>

objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Tw1_Principal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Principal</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>TW1_CPF__c</fullName>
        <externalId>true</externalId>
        <label>CPF</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Cal_Servico_Repo_AggregateContact.cls
public with sharing class Cal_Servico_Repo_AggregateContact {
    
    public Contact GetContatoById(String id)
    {
    	List<Contact> retorno =  [
		    	SELECT id,Tw1_CPF__c, Name,Email,Phone, AccountID
		    	FROM contact
 		    	WHERE
		    	Id = :Id];
		    	
		if(retorno.Size() == 0)
    		return null;
    	else
    		return retorno[0];
    }
    
    public List<AccountContactRelation> GetListaContatosPrincipaisDeUmaConta(string accountId)
    {
       return [SELECT 
               id,
               AccountID, 
               Account.Name,
               ContactId,
               Contact.Name,
               Tw1_Principal__c
		       FROM AccountContactRelation WHERE AccountId =:accountId];
    }
}