objects/Inadimpl_ncia_Timeline_Fases__mdt.object
<CustomObject>
    <fields>
        <fullName>Fase_Value__c</fullName>
        <label>Fase Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Inadimplência Timeline Fase</label>
    <pluralLabel>Inadimplência Timeline Fases</pluralLabel>
</CustomObject>

objects/TimeLine_Fase_Inadimpl_ncia__c.object
<CustomObject>
    <fields>
        <fullName>Data_Fim__c</fullName>
        <label>Data Fim</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Inicio__c</fullName>
        <label>Data Início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fase__c</fullName>
        <label>Fase</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inadimplencia__c</fullName>
        <label>Inadimplência</label>
        <referenceTo>TW1_Inadimplencia__c</referenceTo>
        <relationshipLabel>TimeLine Fase Inadimplência</relationshipLabel>
        <relationshipName>TimeLine_Fase_Inadimplencia</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TimeLine Fase Inadimplência</label>
    <nameField>
        <label>TimeLine Fase Inadimplência Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TimeLine Fase Inadimplência</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Inadimplencia__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amigável</fullName>
                    <default>true</default>
                    <label>Amigável</label>
                </value>
                <value>
                    <fullName>Extrajudicial</fullName>
                </value>
                <value>
                    <fullName>Judicial</fullName>
                </value>
                <value>
                    <fullName>Concluída</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inadimplência</label>
    <nameField>
        <displayFormat>IN# {YYYY}{MM}{0000}</displayFormat>
        <label>Inadimplência</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inadimplências</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Cal_Servico_Application_Inadimplen_Fases.cls
public class Cal_Servico_Application_Inadimplen_Fases {
    
	/*
     * Método responsável por verificar se o status do objeto TimeLine_Fase_Inadimpl_ncia__c
     * está presente no Inadimpl_ncia_Timeline_Fases__mdt Metadata Type
     */
    public void verificaFaseMetadata(TimeLine_Fase_Inadimpl_ncia__c so){
        
        System.debug(' --- (TimeLine_Fase_Inadimpl_ncia__c) so --- ');
        System.debug(so);
        
        List<Inadimpl_ncia_Timeline_Fases__mdt> timelineFasesMeta = (List<Inadimpl_ncia_Timeline_Fases__mdt>)
		[
            SELECT Id 
            FROM Inadimpl_ncia_Timeline_Fases__mdt 
            WHERE Fase_Value__c = :so.Fase__c
        ];
        
        System.debug(' --- (List<Inadimpl_ncia_Timeline_Fases__mdt>) timelineFasesMeta --- ');
        System.debug(timelineFasesMeta);
        
        if(timelineFasesMeta.size() == 0){
            
            System.debug(' --- timelineFasesMeta size vazio. Exception --- ');
            
            throw new Cal_Cls_Infra_Exception('Fase selecionada não corresponde a um registro no Inadimplência TimeLine Fases Custom Metadata Type');
        }
    }
    
    public static void insereInadimplenciaFase(TW1_Inadimplencia__c inadimplencia){
        System.debug('--- INÍCIO DO MÉTODO insereInadimplenciaFase ---');
        
        TimeLine_Fase_Inadimpl_ncia__c inadimplenciaFase = new TimeLine_Fase_Inadimpl_ncia__c();
        inadimplenciaFase.Data_Inicio__c = Date.today();
        inadimplenciaFase.Inadimplencia__c = inadimplencia.Id;
        inadimplenciaFase.Fase__c = inadimplencia.TW1_Fase__c;
        inadimplenciaFase.Data_Fim__c = null;
        
        System.debug('inadimplenciaFase a ser inserido:');
        System.debug(inadimplenciaFase);
        
        insert inadimplenciaFase;
    }
    
    public static void atualizaInadimplenciaFase(TW1_Inadimplencia__c oldInadimplencia){
        List<TimeLine_Fase_Inadimpl_ncia__c> listaInadimplenciaFases = (List<TimeLine_Fase_Inadimpl_ncia__c>)
            [
                SELECT Id
                FROM TimeLine_Fase_Inadimpl_ncia__c
                WHERE Inadimplencia__c = :oldInadimplencia.Id
                AND Data_Fim__c = NULL
            ];
        
        if(listaInadimplenciaFases.size() > 0){
            TimeLine_Fase_Inadimpl_ncia__c inadimplenciaFase = listaInadimplenciaFases.get(0);
            
            inadimplenciaFase.Data_Fim__c = Date.today();
            
            update inadimplenciaFase;
        }
    }
    
}