objects/NTFS__c.object
<CustomObject>
    <fields>
        <fullName>Forma_de_Pagamento_Picklist__c</fullName>
        <label>Forma de Pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dinheiro</fullName>
                </value>
                <value>
                    <fullName>Cartão Crédito</fullName>
                </value>
                <value>
                    <fullName>Cartão Caixa</fullName>
                </value>
                <value>
                    <fullName>Cartão Caixa ELO</fullName>
                </value>
                <value>
                    <fullName>Visa Vale</fullName>
                </value>
                <value>
                    <fullName>Visa Platinum</fullName>
                </value>
                <value>
                    <fullName>Visa Infinite</fullName>
                </value>
                <value>
                    <fullName>Clube Rio Design</fullName>
                </value>
                <value>
                    <fullName>Dinheiro(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Débito(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Crédito(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Debito</fullName>
                    <label>Cartão Débito</label>
                </value>
                <value>
                    <fullName>Aplicativo</fullName>
                </value>
                <value>
                    <fullName>Aplicativo(FDS)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NTFS (Cliente)</relationshipLabel>
        <relationshipName>NTFS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Participante__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participante</label>
        <referenceTo>Participante__c</referenceTo>
        <relationshipLabel>NTFS</relationshipLabel>
        <relationshipName>NTFS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Promocao__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promoção</label>
        <referenceTo>TW1_Parametros_Promocao__c</referenceTo>
        <relationshipLabel>NTFS</relationshipLabel>
        <relationshipName>NTFS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>NTFS</relationshipLabel>
        <relationshipName>NTFS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_RS__c</fullName>
        <label>Valor (R$)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>NTFS</label>
    <nameField>
        <label>Número da NTFS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NTFS</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Participante__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Antigo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Antigo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participantes</relationshipLabel>
        <relationshipName>Participantes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Dia_da_participacao__c</fullName>
        <label>Dia da participação</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Novo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Novo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Promocao__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promoção</label>
        <referenceTo>TW1_Parametros_Promocao__c</referenceTo>
        <relationshipLabel>Participantes</relationshipLabel>
        <relationshipName>Participantes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipLabel>Participantes</relationshipLabel>
        <relationshipName>Participantes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Participante</label>
    <nameField>
        <displayFormat>PA#{000000}</displayFormat>
        <label>Participante</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Participacao_diaria__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Antigo__c</fullName>
        <formula>TW1_Participante__r.TW1_Antigo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Antigo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>PersonAccount</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Participações diárias</relationshipLabel>
        <relationshipName>Participacoes_diarias</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Data_de_participacao__c</fullName>
        <label>Data de participação</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Formas_de_Pagamento__c</fullName>
        <label>Formas de Pagamento</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dinheiro</fullName>
                </value>
                <value>
                    <fullName>Cartão Crédito</fullName>
                </value>
                <value>
                    <fullName>Cartão Caixa</fullName>
                </value>
                <value>
                    <fullName>Cartão Caixa ELO</fullName>
                </value>
                <value>
                    <fullName>Visa Vale</fullName>
                </value>
                <value>
                    <fullName>Visa Platinum</fullName>
                </value>
                <value>
                    <fullName>Visa Infinite</fullName>
                </value>
                <value>
                    <fullName>Cartão Debito</fullName>
                    <label>Cartão Débito</label>
                </value>
                <value>
                    <fullName>Clube Rio Design</fullName>
                </value>
                <value>
                    <fullName>Dinheiro(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Débito(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Crédito(FDS)</fullName>
                </value>
                <value>
                    <fullName>Aplicativo</fullName>
                </value>
                <value>
                    <fullName>Aplicativo(FDS)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Novo__c</fullName>
        <formula>TW1_Participante__r.TW1_Novo__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Novo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Participante__c</fullName>
        <label>Participante</label>
        <referenceTo>Participante__c</referenceTo>
        <relationshipLabel>Participações diárias</relationshipLabel>
        <relationshipName>TW1_Participacoes_diarias</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TW1_Valor__c</fullName>
        <label>Valor (R$)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Participação diária</label>
    <nameField>
        <displayFormat>PD#{0000000}</displayFormat>
        <label>Part. Diária</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participações diárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TW1_Shopping__c.object
<CustomObject>
    
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TW1_Ancar_NotaFiscal_Participante_cls.cls
public with sharing class TW1_Ancar_NotaFiscal_Participante_cls {
	
    public static void processoParticipante(NTFS__c Ntfs)
    {
        
		//Buscar participante por shopping e Cliente
		List<Participante__c> participante = [Select Id,TW1_Antigo__c,TW1_Dia_da_participacao__c,TW1_Novo__c,TW1_Promocao__c,TW1_Shopping__c,TW1_Cliente__c
            From Participante__c where TW1_Shopping__c=:Ntfs.TW1_Shopping__c And TW1_Cliente__c=:Ntfs.TW1_Cliente__c Order By CreatedDate desc];
        
        if(participante == null || participante.size() == 0){
            //Criar registro de participante e criar registro de participaçao diaria
            Participante__c participanteNovo = new Participante__c();
            participanteNovo.TW1_Novo__c = true;
            participanteNovo.TW1_Dia_da_participacao__c = DateTime.now().Date();
            participanteNovo.TW1_Cliente__c = Ntfs.TW1_Cliente__c;
            participanteNovo.TW1_Shopping__c = Ntfs.TW1_Shopping__c;
            participanteNovo.TW1_Promocao__c = Ntfs.TW1_Promocao__c;
            insert participanteNovo;
            
            TW1_Participacao_diaria__c participacaoDiaria = new TW1_Participacao_diaria__c();
            participacaoDiaria.TW1_Formas_de_Pagamento__c = Ntfs.Forma_de_Pagamento_Picklist__c;
            participacaoDiaria.TW1_Data_de_participacao__c = DateTime.now().Date();
            participacaoDiaria.TW1_Participante__c = participanteNovo.Id;
            participacaoDiaria.TW1_Valor__c = Ntfs.TW1_Valor_RS__c;
            participacaoDiaria.TW1_Cliente__c = Ntfs.TW1_Cliente__c;
            
            insert participacaoDiaria;
            
            Ntfs.TW1_Participante__c = participanteNovo.Id;
        }
        else{
            boolean participouflag = true;
            
                for(Participante__c participanteCorrente : participante){
                
                if(participanteCorrente.TW1_Promocao__c == Ntfs.TW1_Promocao__c){
                    //- Participante Novo/Antigo - Concatenar participação diaria
                    Date data = DateTime.now().Date(); 
                    //Buscar registros de participação diaria para o dia vingente
                    List<TW1_Participacao_diaria__c> participacaoDiariaget = [Select Id,TW1_Data_de_participacao__c,TW1_Formas_de_Pagamento__c,TW1_Participante__c,TW1_Valor__c From TW1_Participacao_diaria__c where TW1_Cliente__c=:Ntfs.TW1_Cliente__c And TW1_Data_de_participacao__c=:data];
	                    
                    if(participacaoDiariaget.size() > 0 ){
                        //Somar o valor da nota nocampo valor da participação diaria
                        participacaoDiariaget[0].TW1_Data_de_participacao__c = DateTime.now().Date(); 
                        participacaoDiariaget[0].TW1_Valor__c += Ntfs.TW1_Valor_RS__c;
                        participacaoDiariaget[0].TW1_Formas_de_Pagamento__c = participacaoDiariaget[0].TW1_Formas_de_Pagamento__c + ';' + Ntfs.Forma_de_Pagamento_Picklist__c;
                        
                        update participacaoDiariaget;
                        
                        Ntfs.TW1_Participante__c = participanteCorrente.Id;
                        
                    }else{
                        //Criar registro de participante e criar registro de participaçao diaria
                        TW1_Participacao_diaria__c participacaoDiaria = new TW1_Participacao_diaria__c();
                        participacaoDiaria.TW1_Formas_de_Pagamento__c = Ntfs.Forma_de_Pagamento_Picklist__c;
                        participacaoDiaria.TW1_Data_de_participacao__c = DateTime.now().Date();
                        participacaoDiaria.TW1_Participante__c = participanteCorrente.Id;
                        participacaoDiaria.TW1_Valor__c = Ntfs.TW1_Valor_RS__c;
                        participacaoDiaria.TW1_Cliente__c = Ntfs.TW1_Cliente__c;
                
                		insert participacaoDiaria;
                        
                        Ntfs.TW1_Participante__c = participanteCorrente.Id;
                    }
                       
            		 participouflag = false;
                }
                    
              }
            
            //participante Antigo- flag - mas primeira vez nessa promoção - e primeira vez na participação diaria
            if(participouflag){
                //Criar registro de participante e criar registro de participaçao diaria
                Participante__c participanteNovo = new Participante__c();
                participanteNovo.TW1_Antigo__c = true;
                participanteNovo.TW1_Dia_da_participacao__c = DateTime.now().Date();
                participanteNovo.TW1_Cliente__c = Ntfs.TW1_Cliente__c;
                participanteNovo.TW1_Shopping__c = Ntfs.TW1_Shopping__c;
                participanteNovo.TW1_Promocao__c = Ntfs.TW1_Promocao__c;
                insert participanteNovo;
                
                TW1_Participacao_diaria__c participacaoDiaria = new TW1_Participacao_diaria__c();
                participacaoDiaria.TW1_Formas_de_Pagamento__c = Ntfs.Forma_de_Pagamento_Picklist__c;
                participacaoDiaria.TW1_Data_de_participacao__c = DateTime.now().Date();
                participacaoDiaria.TW1_Participante__c = participanteNovo.Id;
                participacaoDiaria.TW1_Valor__c = Ntfs.TW1_Valor_RS__c;
                participacaoDiaria.TW1_Cliente__c = Ntfs.TW1_Cliente__c;
                
                insert participacaoDiaria;
                
                Ntfs.TW1_Participante__c = participanteNovo.Id;
            }
        }
    }
}