objects/Product2.object
<CustomObject>
    <fields>
        <fullName>TW1_Bloco__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Bloco vinculado a Unidade</description>
        <label>Bloco</label>
        <referenceTo>TW1_Bloco__c</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Unidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Bloco_UAU__c</fullName>
        <formula>TW1_Bloco__r.TW1_Codigo_Bloco_UAU__c</formula>
        <label>Código Bloco ERP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Conta_UAU__c</fullName>
        <formula>TW1_Conta__r.Tw1_Codigo_Cliente_UAU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Codigo Conta ERP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Empreendimento_UAU__c</fullName>
        <formula>TW1_Bloco__r.TW1_Empreendimento__r.TW1_Codigo_Obra_UAU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código Empreendimento ERP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Empresa_UAU__c</fullName>
        <formula>TW1_Bloco__r.TW1_Empreendimento__r.TW1_Empresa__r.TW1_cod_empresa_UAU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código Empresa ERP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Obra_UAU__c</fullName>
        <formula>TW1_Bloco__r.TW1_Codigo_Obra_UAU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código Obra ERP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Personalizacao_UAU__c</fullName>
        <description>Código de Personalização do UAU</description>
        <externalId>true</externalId>
        <label>Código Personalização ERP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Produto_UAU__c</fullName>
        <formula>TW1_Bloco__r.TW1_Codigo_Produto_UAU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Codigo Produto ERP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Conta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unidades</relationshipLabel>
        <relationshipName>Produtos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Data_Averbacao_Habite_se__c</fullName>
        <description>Data que o Habite-se foi averbado.</description>
        <label>Data Averbação do Habite-se</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_Habite_se__c</fullName>
        <description>Informar a data do Habite-se</description>
        <label>Data do Habite-se</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Data_da_Venda__c</fullName>
        <label>Data da Venda</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Empreendimento__c</fullName>
        <formula>TW1_Bloco__r.TW1_Empreendimento__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Empreendimento</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Empresa__c</fullName>
        <formula>TW1_Bloco__r.TW1_Empreendimento__r.TW1_Empresa__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Empresa</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Nome_Bloco__c</fullName>
        <formula>TW1_Bloco__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TW1_Nome_Bloco</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Venda__c</fullName>
        <externalId>true</externalId>
        <label>Número da Venda</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Saldo_Devedor_UAU__c</fullName>
        <label>Saldo Devedor ERP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status da Unidade</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Disponível</fullName>
                </value>
                <value>
                    <fullName>Vendido</fullName>
                </value>
                <value>
                    <fullName>Fora de venda</fullName>
                </value>
                <value>
                    <fullName>Reservado</fullName>
                </value>
                <value>
                    <fullName>Proposta</fullName>
                </value>
                <value>
                    <fullName>Quitado</fullName>
                </value>
                <value>
                    <fullName>Escriturado</fullName>
                </value>
                <value>
                    <fullName>Em venda</fullName>
                </value>
                <value>
                    <fullName>Suspenso</fullName>
                </value>
                <value>
                    <fullName>Em acerto</fullName>
                </value>
                <value>
                    <fullName>Dação</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Unidade__c</fullName>
        <description>Número da Unidade</description>
        <label>Unidade</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_Total_Pago_UAU__c</fullName>
        <label>Valor Total Pago ERP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_da_Venda_UAU__c</fullName>
        <label>Valor da Venda ERP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_de_Venda_Atualizado_UAU__c</fullName>
        <label>Valor de Venda Atualizado ERP</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Bloco__c.object
<CustomObject>
    <description>Bloco vinculado ao Empreendimento</description>
    <fields>
        <fullName>TW1_Codigo_Bloco_UAU__c</fullName>
        <description>Código do Bloco no UAU</description>
        <label>Código do Bloco no ERP</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Obra_UAU__c</fullName>
        <description>Código da Obra no ERP</description>
        <label>Codigo Obra ERP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Produto_UAU__c</fullName>
        <description>Código do produto no UAU</description>
        <externalId>true</externalId>
        <label>Código do produto no ERP</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Empreendimento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo de relacionamento com  objeto Empreendimento</description>
        <label>Empreendimento</label>
        <referenceTo>TW1_Empreendimento__c</referenceTo>
        <relationshipLabel>Blocos</relationshipLabel>
        <relationshipName>Blocos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Responsavel_Manutencao_Vistoria__c</fullName>
        <label>Responsável Manutenção/Vistoria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Engenharia</fullName>
                    <default>true</default>
                    <label>Engenharia</label>
                </value>
                <value>
                    <fullName>Manutenção</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bloco</label>
    <nameField>
        <label>Nome do Bloco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Empreendimento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Codigo_Obra_UAU__c</fullName>
        <externalId>true</externalId>
        <label>Código da Obra no ERP</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TW1_Empresa__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Empresa vinculada ao Empreendimento</description>
        <label>Empresa</label>
        <referenceTo>TW1_Empresa__c</referenceTo>
        <relationshipLabel>Empreendimentos</relationshipLabel>
        <relationshipName>Empreendimentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Empresa__c.object
<CustomObject>
    <fields>
        <fullName>TW1_cod_empresa_UAU__c</fullName>
        <description>Código da Empresa no UAU</description>
        <externalId>true</externalId>
        <inlineHelpText>Código da Empresa no UAU</inlineHelpText>
        <label>Código Empresa ERP</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Empresa</label>
    <nameField>
        <label>Razão Social</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Cal_Servico_Repo_AggregateProduct.cls
public with sharing class Cal_Servico_Repo_AggregateProduct {
    /// Busca produto pelo ID
    public Product2 GetProductById(string Id)
    {
        List<Product2> retorno =  [
            SELECT 
            id,
            TW1_Unidade__c,
            TW1_Conta__c,
            TW1_Codigo_Personalizacao_UAU__c, 
            TW1_Data_Habite_se__c, 
            TW1_Data_Averbacao_Habite_se__c, 
            TW1_Bloco__c, 
            TW1_Numero_Venda__c,
            TW1_Empresa__c,
            TW1_Empreendimento__c,
            TW1_Codigo_Empresa_UAU__c,		
            TW1_Codigo_Empreendimento_UAU__c,
            TW1_Codigo_Bloco_UAU__c,                   
            TW1_Data_da_Venda__c,
            TW1_Saldo_Devedor_UAU__c,
            TW1_Valor_da_Venda_UAU__c,
            TW1_Valor_de_Venda_Atualizado_UAU__c,
            TW1_Valor_Total_Pago_UAU__c,
            TW1_Codigo_Conta_UAU__c,
            TW1_Bloco__r.TW1_Responsavel_Manutencao_Vistoria__c
            FROM Product2 
            WHERE 
            Id = :Id];
        
        if(retorno.Size() == 0)
            return null;
        else
            return retorno[0];
    }
    
    /// Busca lista de unidades vendidas, essas estão com o contrato ativo e fluxo de pagamento em aberto
    public Map<Id, Product2> GetListaUnidadesContratosAtivos()
    {
        Map<Id, Product2> mapper = new Map<Id, Product2>([SELECT 
                                                          id, 
                                                          TW1_Codigo_Bloco_UAU__c,
                                                          TW1_Unidade__c,
                                                          TW1_Codigo_Empreendimento_UAU__c,
                                                          TW1_Codigo_Empresa_UAU__c,
                                                          TW1_Codigo_Personalizacao_UAU__c,
                                                          TW1_Numero_Venda__c,
                                                          TW1_Data_da_Venda__c,
                                                          TW1_Saldo_Devedor_UAU__c,
                                                          TW1_Valor_da_Venda_UAU__c,
                                                          TW1_Valor_de_Venda_Atualizado_UAU__c,
                                                          TW1_Valor_Total_Pago_UAU__c
                                                          FROM Product2
                                                          WHERE Tw1_Status__c = 'Vendida' AND TW1_Numero_Venda__c != null]);
        return mapper;
    }
    
    /// Busca lista de unidades onde o Id é o nome da unidade
    public Map<string, Product2> GelListaUnidadesPorBloco(Id idBloco)
    {
        /// Monta mapper com o nome da unidade como chave
        Map<string, Product2> mapper = new Map<string, Product2>();
        
        /// Busca todas as unidades de um determinado bloco.
        for(Product2 produto : [SELECT id, Name FROM Product2 WHERE TW1_Bloco__c = :idBloco])
            mapper.put(produto.Name, produto);
        
        return mapper;
    }
    
    public void Atualizar(Product2 unidade)
    {
        update unidade;
    }
    
    public void Incluir(Product2 unidade)
    {
        insert unidade;
    }
    
    public void AtualizarRange(List<Product2> unidades)
    {
        update unidades;
    }
    
    public void IncluirRange(List<Product2> unidades)
    {
        insert unidades;
    }
    /// Inserir ou atualizar empresa
    public void InserirAtualizarEmpresa(TW1_Empresa__c empresa)
    {
        List<TW1_Empresa__c> empresas = [select id FROM  TW1_Empresa__c where TW1_cod_empresa_UAU__c = :empresa.TW1_cod_empresa_UAU__c]; 
        
        if(empresas.Size() == 0)
            insert empresa;
        else
        {
            empresa.Id = empresas[0].Id;
            update empresa;
        }        
    }
    
    public void InserirAtualizarEmpreendimento(TW1_Empreendimento__c empreendimento)
    {
        List<TW1_Empreendimento__c> empreendimentos = [select id FROM  TW1_Empreendimento__c where TW1_Codigo_Obra_UAU__c = :empreendimento.TW1_Codigo_Obra_UAU__c]; 
        
        if(empreendimentos.Size() == 0)
            insert empreendimento;
        else
        {
            empreendimento.Id = empreendimentos[0].Id;
            update empreendimento;
        }    
    }
    
    public void InserirAtualizarBloco(TW1_Bloco__c bloco)
    {
        List<TW1_Bloco__c> blocos = [select id FROM  TW1_Bloco__c where TW1_Codigo_Produto_UAU__c = :bloco.TW1_Codigo_Produto_UAU__c]; 
        
        if(blocos.Size() == 0)
            insert bloco;
        else
        {
            bloco.Id = blocos[0].Id;
            update bloco;
        }    
    }   
    
    public Product2 GetUnidadePorEmpresaObraVenda(string codigoEmpresa, string codigoObra, string numeroVenda)
    {
        List<Product2> listaUnidades = [SELECT 
                                        id,
                                        name,
                                        TW1_Conta__c,
                                        TW1_Unidade__c,
                                        TW1_Codigo_Personalizacao_UAU__c, 
                                        TW1_Data_Habite_se__c, 
                                        TW1_Data_Averbacao_Habite_se__c, 
                                        TW1_Bloco__c, 
                                        TW1_Numero_Venda__c,
                                        TW1_Empresa__c,
                                        TW1_Empreendimento__c,                                        
                                        TW1_Codigo_Empresa_UAU__c,		
                                        TW1_Codigo_Empreendimento_UAU__c,
                                        TW1_Codigo_Bloco_UAU__c,
                                        TW1_Nome_Bloco__c,
                                        TW1_Data_da_Venda__c,
                                        TW1_Saldo_Devedor_UAU__c,
                                        TW1_Valor_da_Venda_UAU__c,
                                        TW1_Valor_de_Venda_Atualizado_UAU__c,
                                        TW1_Valor_Total_Pago_UAU__c,
                                        TW1_Codigo_Conta_UAU__c,
                                        TW1_Bloco__r.TW1_Responsavel_Manutencao_Vistoria__c
                                        FROM Product2  
                                        WHERE TW1_Codigo_Empresa_UAU__c =:codigoEmpresa 
                                        AND TW1_Codigo_Empreendimento_UAU__c =: codigoObra 
                                        AND TW1_Numero_Venda__c =:numeroVenda];
        
        if(listaUnidades.size() <1)
            return null;
        else
            return listaUnidades[0];
    }
    
    public Product2 GetUnidadePorEmpresaObraPersonalisacao(string codigoEmpresa, string codigoObra, string codigoPersonalisacao)
    {
        List<Product2> listaUnidades = [SELECT 
                                        id,
                                        name,
                                        TW1_Conta__c,
                                        TW1_Unidade__c,
                                        TW1_Codigo_Personalizacao_UAU__c, 
                                        TW1_Data_Habite_se__c, 
                                        TW1_Data_Averbacao_Habite_se__c, 
                                        TW1_Bloco__c, 
                                        TW1_Numero_Venda__c,
                                        TW1_Empresa__c,
                                        TW1_Empreendimento__c,                                        
                                        TW1_Codigo_Empresa_UAU__c,		
                                        TW1_Codigo_Empreendimento_UAU__c,
                                        TW1_Codigo_Produto_UAU__c,
                                        TW1_Codigo_Bloco_UAU__c,
                                        TW1_Nome_Bloco__c,
                                        TW1_Data_da_Venda__c,
                                        TW1_Saldo_Devedor_UAU__c,
                                        TW1_Valor_da_Venda_UAU__c,
                                        TW1_Valor_de_Venda_Atualizado_UAU__c,
                                        TW1_Valor_Total_Pago_UAU__c,
                                        TW1_Codigo_Conta_UAU__c,
                                        TW1_Bloco__r.TW1_Responsavel_Manutencao_Vistoria__c
                                        FROM Product2  
                                        WHERE TW1_Codigo_Empresa_UAU__c =:codigoEmpresa 
                                        AND TW1_Codigo_Produto_UAU__c =: codigoObra 
                                        AND TW1_Codigo_Personalizacao_UAU__c =:codigoPersonalisacao];
        
        if(listaUnidades.size() <1)
            return null;
        else
            return listaUnidades[0];
    }
    
    
    public List<Product2> GetTodasPropriedadesDeUmCLiente(string accountId)
    {
        return [SELECT 
                id,
                name,
                TW1_Unidade__c,
                TW1_Conta__c,
                TW1_Codigo_Personalizacao_UAU__c, 
                TW1_Data_Habite_se__c, 
                TW1_Data_Averbacao_Habite_se__c, 
                TW1_Bloco__c, 
                TW1_Numero_Venda__c,
                TW1_Empresa__c,
                TW1_Empreendimento__c,
                TW1_Codigo_Empresa_UAU__c,		
                TW1_Codigo_Empreendimento_UAU__c,
                TW1_Codigo_Bloco_UAU__c,
                TW1_Nome_Bloco__c,
                TW1_Data_da_Venda__c,
                TW1_Saldo_Devedor_UAU__c,
                TW1_Valor_da_Venda_UAU__c,
                TW1_Valor_de_Venda_Atualizado_UAU__c,
                TW1_Valor_Total_Pago_UAU__c,
                TW1_Codigo_Conta_UAU__c,
                TW1_Bloco__r.TW1_Responsavel_Manutencao_Vistoria__c
                FROM Product2  
                WHERE TW1_Conta__c = :accountId];
    }
}