objects/TW1_Acoes__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Cliente_Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Principal</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ações</relationshipLabel>
        <relationshipName>Acoes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Fase_Inadimplencia__c</fullName>
        <label>Fase da Inadimplencia</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amigável</fullName>
                </value>
                <value>
                    <fullName>Judicial</fullName>
                </value>
                <value>
                    <fullName>Extrajudicial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Inadimplencia__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Inadimplência</label>
        <referenceTo>TW1_Inadimplencia__c</referenceTo>
        <relationshipLabel>Ações</relationshipLabel>
        <relationshipName>TW1_Acoes_Inadimplencia</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Motivo_Cancelamento__c</fullName>
        <label>Motivo Cancelamento</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Não iniciada</fullName>
                    <default>true</default>
                    <label>Não iniciada</label>
                </value>
                <value>
                    <fullName>Em andamento</fullName>
                </value>
                <value>
                    <fullName>Concluída</fullName>
                </value>
                <value>
                    <fullName>TW1_Cancelada</fullName>
                    <label>Cancelada</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Unidade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unidade</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Ações da Inadimplência</relationshipLabel>
        <relationshipName>TW1_Acoes_Unidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ações</label>
    <nameField>
        <displayFormat>A-{YYYY}{MM}{0000}</displayFormat>
        <label>Nome de Ações</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ações</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TW1_Inadimplencia__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Cliente_Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente Principal</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Inadimplências</relationshipLabel>
        <relationshipName>TW1_Inadimplencias_Conta</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Empreendimento_UAU__c</fullName>
        <formula>TW1_Unidade__r.TW1_Codigo_Empreendimento_UAU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código Empreendimento UAU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Empresa_UAU__c</fullName>
        <formula>TW1_Unidade__r.TW1_Codigo_Empresa_UAU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código Empresa UAU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Codigo_Obra_UAU__c</fullName>
        <formula>TW1_Unidade__r.TW1_Codigo_Obra_UAU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Código Obra UAU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Etapa__c</fullName>
        <label>Etapa</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nova</fullName>
                    <default>true</default>
                    <label>Nova</label>
                </value>
                <value>
                    <fullName>Analisando Transferência de Responsável</fullName>
                </value>
                <value>
                    <fullName>Buscando Contato com Cliente</fullName>
                </value>
                <value>
                    <fullName>Notificando Jucialmente</fullName>
                </value>
                <value>
                    <fullName>Realizando Negociação</fullName>
                </value>
                <value>
                    <fullName>Aguardando Aprovação da Diretoria</fullName>
                </value>
                <value>
                    <fullName>Registrando Trativa</fullName>
                </value>
                <value>
                    <fullName>Aguardando Pagamento</fullName>
                </value>
                <value>
                    <fullName>Analisando Negociação</fullName>
                </value>
                <value>
                    <fullName>Gerando Boleto</fullName>
                </value>
                <value>
                    <fullName>Negociação Definida/Aguardando Conclusão da Inadimplência</fullName>
                </value>
                <value>
                    <fullName>Analisando Inadimplência</fullName>
                </value>
                <value>
                    <fullName>Aguardando Data Postergação</fullName>
                </value>
                <value>
                    <fullName>Aguardando encerramento da Inadimplência</fullName>
                </value>
                <value>
                    <fullName>Aguardando Aprovação da Gerência</fullName>
                </value>
                <value>
                    <fullName>Analisando Distrato</fullName>
                </value>
                <value>
                    <fullName>Analisando Inclusão das Parcelas no Financiamento</fullName>
                </value>
                <value>
                    <fullName>Distrato Realizado</fullName>
                </value>
                <value>
                    <fullName>Aguardando tempo para inicio de cobrança</fullName>
                </value>
                <value>
                    <fullName>Pausada</fullName>
                </value>
                <value>
                    <fullName>Encerrada pelo UAU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Etapa_pre_pausa__c</fullName>
        <label>Etapa pré-pausa</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Fase__c</fullName>
        <label>Fase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amigável</fullName>
                    <default>true</default>
                    <label>Amigável</label>
                </value>
                <value>
                    <fullName>Extrajudicial</fullName>
                </value>
                <value>
                    <fullName>Judicial</fullName>
                </value>
                <value>
                    <fullName>Concluída</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Maior_Data_Vencimento__c</fullName>
        <label>Maior Data Vencimento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Parcelas__c</fullName>
        <label>Numero Parcelas Abertas</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Numero_Venda__c</fullName>
        <label>Número da Venda</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_Tempo_Inadimplencia__c</fullName>
        <label>Tempo de Inadimplência</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_Unidade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unidade</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inadimplências</relationshipLabel>
        <relationshipName>TW1_Inadimplencia_Unidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_Principal__c</fullName>
        <label>Valor Principal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_Reajustado__c</fullName>
        <label>Valor Reajustado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Inadimplência</label>
    <nameField>
        <displayFormat>IN# {YYYY}{MM}{0000}</displayFormat>
        <label>Inadimplência</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inadimplências</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Parcela_Inadimplencia__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Inadimplencia__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Inadimplência</label>
        <referenceTo>TW1_Inadimplencia__c</referenceTo>
        <relationshipLabel>Parcelas da Inadimplência</relationshipLabel>
        <relationshipName>TW1_Parcela_Inadimplencia_Inadimplencia</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Unidade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unidade</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Parcelas da Inadimplência</relationshipLabel>
        <relationshipName>TW1_Parcela_Inadimplencia_Unidade</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Valor_Reajustado__c</fullName>
        <label>Valor Reajustado</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Parcela da Inadimplência</label>
    <nameField>
        <displayFormat>PI# {00000000}</displayFormat>
        <label>Nome de Parcela da Inadimplência</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcelas da Inadimplência</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Cal_Servico_Repo_AggregateInadiple.cls
public class Cal_Servico_Repo_AggregateInadiple {
	
    public TW1_Inadimplencia__c GetInadimplenciaByID(String id)
    {
        List<TW1_Inadimplencia__c> retorno =  [
		    	SELECT id,TW1_Etapa__c,TW1_Etapa_pre_pausa__c
		    	FROM TW1_Inadimplencia__c
 		    	WHERE
		    	Id = :Id];
		    	
		if(retorno.Size() == 0)
    		return null;
    	else
    		return retorno[0];
    }
    
    public List<TW1_Inadimplencia__c> GetInadimplenciasAtivas()
    {
        List<TW1_Inadimplencia__c> retorno =  [
		    	SELECT 
            		id,
            		TW1_Etapa__c,
            		TW1_Etapa_pre_pausa__c,
            		TW1_Codigo_Obra_UAU__c,
					TW1_Codigo_Empreendimento_UAU__c,
					TW1_Numero_Venda__c,
					TW1_Codigo_Empresa_UAU__c 
		    	FROM TW1_Inadimplencia__c
 		    	WHERE
		    	TW1_Fase__c != 'Concluída' ];
		
        return retorno;
    }
 
    public TW1_Inadimplencia__c GetInadimplenciaByAccountIdEProductIdAtivas(string accountId, string productId)
    {
        List<TW1_Inadimplencia__c> retorno =  [
		    	SELECT 
            		id,
            		TW1_Etapa__c, 
            		TW1_Etapa_pre_pausa__c,
                    TW1_Valor_Reajustado__c,
                    TW1_Valor_Principal__c,
                    TW1_Numero_Parcelas__c,
                    TW1_Tempo_Inadimplencia__c,
                    TW1_Maior_Data_Vencimento__c
		    	FROM 
            		TW1_Inadimplencia__c
 		    	WHERE
		    		TW1_Cliente_Principal__c = :accountId
        			AND TW1_Unidade__c = :productId
        			AND TW1_Fase__c != 'Concluída' ];
		    	
		if(retorno.Size() == 0)
    		return null;
    	else
    		return retorno[0];
    }   
    
    public List<TW1_Parcela_Inadimplencia__c> GetParcelasDeUmaInadimplencia(string inadimplenciaId)
    {
        List<TW1_Parcela_Inadimplencia__c> retorno = [SELECT id FROM TW1_Parcela_Inadimplencia__c WHERE Id = :inadimplenciaId];
        return retorno;
    }
    
    public void Modify(TW1_Inadimplencia__c inadimplencia)
    {
        update inadimplencia;
    }
    
    public List<TW1_Acoes__c> GetAcoesEmAbertoByInadimplenicaEFase(Id idInadimplencia, string faseConsulta)
    {
        List<TW1_Acoes__c> retorno = [SELECT 
                                      	id, 
                                      	TW1_Motivo_Cancelamento__c,
                                      	TW1_Fase_Inadimplencia__c,
                                      	TW1_Inadimplencia__c
                                      FROM 
                                      	TW1_Acoes__c 
                                      WHERE TW1_Inadimplencia__c = :idInadimplencia 
                                     	AND TW1_Status__c != 'TW1_Cancelada' 
                                      	AND TW1_Status__c != 'Concluída'];
        return retorno;
    }    
}