objects/TW1_Agendamento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Data_do_Agendamento__c</fullName>
        <label>Data do Agendamento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TW1_Empreendimento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Empreendimento</label>
        <referenceTo>TW1_Empreendimento__c</referenceTo>
        <relationshipLabel>Agendamentos</relationshipLabel>
        <relationshipName>Agendamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Hora__c</fullName>
        <label>Hora</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>08:00</fullName>
                </value>
                <value>
                    <fullName>08:30</fullName>
                </value>
                <value>
                    <fullName>09:00</fullName>
                </value>
                <value>
                    <fullName>09:30</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                </value>
                <value>
                    <fullName>10:30</fullName>
                </value>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>16:00</fullName>
                </value>
                <value>
                    <fullName>16:30</fullName>
                </value>
                <value>
                    <fullName>17:00</fullName>
                </value>
                <value>
                    <fullName>17:30</fullName>
                </value>
                <value>
                    <fullName>18:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agendado</fullName>
                </value>
                <value>
                    <fullName>Concluído com sucesso</fullName>
                    <label>Concluído com sucesso - Vistoria Aprovada</label>
                </value>
                <value>
                    <fullName>Cancelado pelo Cliente</fullName>
                </value>
                <value>
                    <fullName>Cancelado pela Engenharia</fullName>
                    <label>Cancelado pela Engenharia/Manutenção</label>
                </value>
                <value>
                    <fullName>Cliente não compareceu</fullName>
                </value>
                <value>
                    <fullName>Cancelado por antecipação</fullName>
                </value>
                <value>
                    <fullName>Concluído Vistoria Reprovada</fullName>
                    <label>Concluído - Vistoria Reprovada</label>
                </value>
                <value>
                    <fullName>Novo</fullName>
                    <isActive>false</isActive>
                    <label>Novo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agendamento</label>
    <nameField>
        <displayFormat>A# {00000000}</displayFormat>
        <label>Agenda</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agendamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Empreendimento__c.object
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Cal_Servico_Repo_AggregateAgendVistoria.cls
public class Cal_Servico_Repo_AggregateAgendVistoria {
    
    public List< AggregateResult> GetTotalAgendamentosPorEmpreendimentoEDia(string idEmpreendimento, date dataCorrente)
    {
        List<AggregateResult> retorno = [select TW1_Hora__c, COUNT(id) 
                                         from TW1_Agendamento__c
                                         Where TW1_Empreendimento__c = :idEmpreendimento
                                         AND TW1_Data_do_Agendamento__c = :dataCorrente
                                         AND (TW1_Status__c  = 'Novo' OR TW1_Status__c ='Agendado')
                                         Group by TW1_Hora__c];
        
        return retorno;        
    }  
}