objects/TW1_Parametros_Promocao__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Shopping__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shopping</label>
        <referenceTo>TW1_Shopping__c</referenceTo>
        <relationshipName>Promo_es</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Parâmetros da Promoção</label>
    <nameField>
        <label>Nome da Promoção</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parâmetros da Promoções</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TW1_Shopping__c.object
<CustomObject>
    
    <label>Shopping</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shoppings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TR_Ancar_Promo_PromoShop_Tst.cls
/******************************************************************************************************
Author  : Wellington N Rodrigues
Date    : 28/06/2018
Purpose : Classe de Test de TR_Ancar_Promo_PromoShop para buscar promoções de um Shopping - Melhoria
*******************************************************************************************************/
@istest
public with sharing class TR_Ancar_Promo_PromoShop_Tst {

    static testMethod void getPromocoesPorShoppingTst() {

        TW1_Shopping__c paShopping = TR_Ancar_Promo_PromoShop_Mock.criaShopping();
        TW1_Parametros_Promocao__c paPromocao = TR_Ancar_Promo_PromoShop_Mock.criaPromocao(paShopping.id);
        
        RestRequest request = new RestRequest();
        request.requestUri ='/services/apexrest/PromoShop';
        
        request.addParameter('Idshopping', paShopping.Id);
        request.httpMethod = 'GET';
        
        RestContext.request = request;
        System.debug(RestContext.request);
        
        TR_Ancar_Promo_PromoShop_Serv.getPromoShop();
        
    }
    
    static testMethod void getPromocoesPorShopping_ShoppingEmBranco_Tst() {

        TW1_Shopping__c paShopping = TR_Ancar_Promo_PromoShop_Mock.criaShopping();
        TW1_Parametros_Promocao__c paPromocao = TR_Ancar_Promo_PromoShop_Mock.criaPromocao(paShopping.id);
        
        RestRequest request = new RestRequest();
        request.requestUri ='/services/apexrest/PromoShop';
        
        request.addParameter('Idshopping', '');
        request.httpMethod = 'GET';
        
        RestContext.request = request;
        System.debug(RestContext.request);
        
        TR_Ancar_Promo_PromoShop_Serv.getPromoShop();
        
    }
    
    static testMethod void getPromocoesPorShopping_ShoppingErrado_Tst() {

        TW1_Shopping__c paShopping = TR_Ancar_Promo_PromoShop_Mock.criaShopping();
        TW1_Parametros_Promocao__c paPromocao = TR_Ancar_Promo_PromoShop_Mock.criaPromocao(paShopping.id);
        
        RestRequest request = new RestRequest();
        request.requestUri ='/services/apexrest/PromoShop';
        
        request.addParameter('Idshopping', 'a010R000000n9VT');
        request.httpMethod = 'GET';
        
        RestContext.request = request;
        System.debug(RestContext.request);
        
        TR_Ancar_Promo_PromoShop_Serv.getPromoShop();
        
    }

}