objects/TW1_Agendamento__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Caso__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caso</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Agendamentos</relationshipLabel>
        <relationshipName>Agendamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Conta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Conta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agendamentos</relationshipLabel>
        <relationshipName>Agendamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Contato__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contato</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Agendamentos</relationshipLabel>
        <relationshipName>Agendamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Empreendimento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Empreendimento</label>
        <referenceTo>TW1_Empreendimento__c</referenceTo>
        <relationshipLabel>Agendamentos</relationshipLabel>
        <relationshipName>Agendamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TW1_Hora__c</fullName>
        <label>Hora</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>08:00</fullName>
                </value>
                <value>
                    <fullName>08:30</fullName>
                </value>
                <value>
                    <fullName>09:00</fullName>
                </value>
                <value>
                    <fullName>09:30</fullName>
                </value>
                <value>
                    <fullName>10:00</fullName>
                </value>
                <value>
                    <fullName>10:30</fullName>
                </value>
                <value>
                    <fullName>11:00</fullName>
                </value>
                <value>
                    <fullName>11:30</fullName>
                </value>
                <value>
                    <fullName>12:00</fullName>
                </value>
                <value>
                    <fullName>12:30</fullName>
                </value>
                <value>
                    <fullName>13:00</fullName>
                </value>
                <value>
                    <fullName>13:30</fullName>
                </value>
                <value>
                    <fullName>14:00</fullName>
                </value>
                <value>
                    <fullName>14:30</fullName>
                </value>
                <value>
                    <fullName>15:00</fullName>
                </value>
                <value>
                    <fullName>15:30</fullName>
                </value>
                <value>
                    <fullName>16:00</fullName>
                </value>
                <value>
                    <fullName>16:30</fullName>
                </value>
                <value>
                    <fullName>17:00</fullName>
                </value>
                <value>
                    <fullName>17:30</fullName>
                </value>
                <value>
                    <fullName>18:00</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agendado</fullName>
                </value>
                <value>
                    <fullName>Concluído com sucesso</fullName>
                    <label>Concluído com sucesso - Vistoria Aprovada</label>
                </value>
                <value>
                    <fullName>Cancelado pelo Cliente</fullName>
                </value>
                <value>
                    <fullName>Cancelado pela Engenharia</fullName>
                    <label>Cancelado pela Engenharia/Manutenção</label>
                </value>
                <value>
                    <fullName>Cliente não compareceu</fullName>
                </value>
                <value>
                    <fullName>Cancelado por antecipação</fullName>
                </value>
                <value>
                    <fullName>Concluído Vistoria Reprovada</fullName>
                    <label>Concluído - Vistoria Reprovada</label>
                </value>
                <value>
                    <fullName>Novo</fullName>
                    <isActive>false</isActive>
                    <label>Novo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Unidade__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unidade</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Agendamentos</relationshipLabel>
        <relationshipName>Agendamentos</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Agendamento</label>
    <nameField>
        <displayFormat>A# {00000000}</displayFormat>
        <label>Agenda</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agendamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TW1_Empreendimento__c.object
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome do Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Cal_Servico_Application_AgendVistoria.cls
public with sharing class Cal_Servico_Application_AgendVistoria {
    
    Cal_Servico_Repo_AggregateAgendVistoria agendamentoRepository = new Cal_Servico_Repo_AggregateAgendVistoria();
    
    public List<Cal_Servico_Ctr_AgendVistoria.AgendamentoDto> GetListaAgendamentosPorEmpreendimentoEDia(string idEmpreendimento, Date dataCorrente)
    {
        system.debug('Iniciando consulta de agendamentos para o dia ' + dataCorrente + ' no empreendimento ' + idEmpreendimento);
        
        if(idEmpreendimento == '' || dataCorrente == null)
            throw new Cal_Cls_Infra_Exception('Selecione um empreendimento e uma data para realizar a consulta aos agendamentos.');
        
        List<AggregateResult> consulta = agendamentoRepository.GetTotalAgendamentosPorEmpreendimentoEDia(idEmpreendimento,dataCorrente);
        system.debug('Retorno da consulta: ' + consulta);
        
        system.debug('Iniciando mapeamento para Dto');
        return MapListaAggregateResultAgendamentosParaListaAgenddamentoDto(consulta);
    }
    
    /// Realiza o mapeamento de AggregateResult agendamento para Dto
    public List<Cal_Servico_Ctr_AgendVistoria.AgendamentoDto> MapListaAggregateResultAgendamentosParaListaAgenddamentoDto(List<AggregateResult> source)
    {
        List<Cal_Servico_Ctr_AgendVistoria.AgendamentoDto> retorno = new List<Cal_Servico_Ctr_AgendVistoria.AgendamentoDto>();
        
        for(AggregateResult linha : source)
        {
            system.debug('Processando linha: ' + linha);
            Cal_Servico_Ctr_AgendVistoria.AgendamentoDto dto = new Cal_Servico_Ctr_AgendVistoria.AgendamentoDto();
            dto.Horario = (string)linha.get('TW1_Hora__c');
            dto.Quantidade = (integer)linha.get('expr0');
            retorno.add(dto);
        }
        
        system.debug('Fim do processamento');
        return retorno;        
    }
    
    public TW1_Agendamento__c SalvarAgendamento(Case caso, TW1_Agendamento__c agendamento)
    {        
        if(Agendamento.TW1_Hora__c == null || agendamento.TW1_Hora__c == '' )
            throw new Cal_Cls_Infra_Exception('Selecione um horário.');
        
        agendamento.TW1_Caso__c = caso.Id;
        agendamento.TW1_Empreendimento__c = caso.TW1_ID_Empreendimento__c;
        agendamento.TW1_Unidade__c = caso.TW1_Unidade__c;
        agendamento.TW1_Conta__c = caso.AccountId;
        agendamento.TW1_Contato__c = caso.ContactId;
        agendamento.TW1_Status__c = 'Agendado';
        upsert agendamento;
        return agendamento;
    }    
}