objects/TW1_Parametros_Promocao__c.object
<CustomObject>
    <fields>
        <fullName>TW1_Acumula_Saldo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Acumula Saldo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_CampoVendedor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Campo Vendedor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Concurso_Cultural__c</fullName>
        <label>Concurso Cultural</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sim</fullName>
                </value>
                <value>
                    <fullName>Não</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Contabiliza_Bonus__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Considerar condição especial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Formas_de_Pagamento__c</fullName>
        <label>Formas de Pagamento</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dinheiro</fullName>
                </value>
                <value>
                    <fullName>Cartão Debito</fullName>
                    <label>Cartão Débito</label>
                </value>
                <value>
                    <fullName>Cartão Caixa</fullName>
                </value>
                <value>
                    <fullName>Cartão Caixa ELO</fullName>
                </value>
                <value>
                    <fullName>Visa Vale</fullName>
                </value>
                <value>
                    <fullName>Visa Platinum</fullName>
                </value>
                <value>
                    <fullName>Visa Infinite</fullName>
                </value>
                <value>
                    <fullName>Clube Rio Design</fullName>
                </value>
                <value>
                    <fullName>Dinheiro(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Débito(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Crédito(FDS)</fullName>
                </value>
                <value>
                    <fullName>Aplicativo</fullName>
                </value>
                <value>
                    <fullName>Aplicativo(FDS)</fullName>
                </value>
                <value>
                    <fullName>Cartão Crédito</fullName>
                </value>
                <value>
                    <fullName>CLUBE RDB</fullName>
                    <isActive>false</isActive>
                    <label>CLUBE RDB</label>
                </value>
                <value>
                    <fullName>Cartão Credito</fullName>
                    <isActive>false</isActive>
                    <label>Cartão Credito</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TW1_Imprimir_nome_do_lojista__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Imprimir nome do lojista?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_Troca_por__c</fullName>
        <label>Troca por</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Brinde</fullName>
                </value>
                <value>
                    <fullName>Cupom</fullName>
                </value>
                <value>
                    <fullName>Ambos</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Parâmetros da Promoção</label>
    <nameField>
        <label>Nome da Promoção</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parâmetros da Promoções</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TR_Ancar_Promo_PromoShop_App.cls
public with sharing class TR_Ancar_Promo_PromoShop_App {
    
    TR_Ancar_Promo_Rep repositorio = new TR_Ancar_Promo_Rep();
    
    public list<TR_Ancar_Promo_PromoShop_Serv.PromoShopDto> listaPromoShop(String paShopping, Date paDataAtual){
        System.debug('Pega o id do Shopping:'+paShopping+' e a data atual '+paDataAtual);
        if(paShopping==''){
            return null;
        }else{
            list<TW1_Parametros_Promocao__c> retornoPromoShop = repositorio.ListaPromoShop(paShopping, paDataAtual);

            list<TR_Ancar_Promo_PromoShop_Serv.PromoShopDto> retorno = new list<TR_Ancar_Promo_PromoShop_Serv.PromoShopDto>();

            for( TW1_Parametros_Promocao__c promocao : retornoPromoShop ){
                
                TR_Ancar_Promo_PromoShop_Serv.PromoShopDto listaPromo = new TR_Ancar_Promo_PromoShop_Serv.PromoShopDto();
                
                listaPromo.id = promocao.id;
                listaPromo.trocaPor = promocao.TW1_Troca_por__c;
                listaPromo.formaDePagamento = promocao.TW1_Formas_de_Pagamento__c;
                listaPromo.concursoCultural = promocao.TW1_Concurso_Cultural__c;
                listaPromo.contabilizaBonus = promocao.TW1_Contabiliza_Bonus__c;
                listaPromo.acumulaSaldo = promocao.TW1_Acumula_Saldo__c;
                listaPromo.Name = promocao.Name;
                listaPromo.campoVendedor = promocao.TW1_CampoVendedor__c;
                listaPromo.ImprimirNomeDoLojista = promocao.TW1_Imprimir_nome_do_lojista__c;
                
                retorno.add(listaPromo);
            }

            System.debug('03 - preenche o DTO :'+retorno);
            
            return retorno;
        }
    }  

}