objects/TW1_Custom_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>TW1_BaseProducaoUau__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BaseProduçãoUau</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_LoginUau__c</fullName>
        <label>LoginUau</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_SenhaUau__c</fullName>
        <label>SenhaUAU</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TW1_URLBaseServicoAT__c</fullName>
        <label>URLBaseServicoAT</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>TW1_URLBaseServicoUau__c</fullName>
        <label>URLBaseServicoUau</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>TW1_URLCallBackAT__c</fullName>
        <description>URL de callback do AT, essa URL é do serviço de atualizar status no SalesForce.</description>
        <label>URLCallBackAT</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>TW1_URLCallBackAtualizacaoCadastralUAU__c</fullName>
        <description>URL de CallBack  de atualização cadastral do UAU</description>
        <label>CallBackAtualizacaoCadastralUAU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Custom Settings TW1</label>
</CustomObject>

objects/TW1_Padroes_Inadimplencia__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>TW1_parcelaNaoConciliada__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Parcela Não Conciliada</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TW1_qtdDiasVencimento__c</fullName>
        <label>Quantidade Dias Vencimento</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TW1_urlCallback__c</fullName>
        <label>URL Callback</label>
        <type>Url</type>
    </fields>
    <label>Padrões Inadimplência</label>
</CustomObject>

objects/TW1_Padroes_relacionamento__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>TW1_Tempo_Atualizacao_Cadastral__c</fullName>
        <label>Tempo Atualização Cadastral</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Padrões Relacionamento</label>
</CustomObject>

classes/Cal_Servico_Repo_AggregateCustomSe.cls
public class Cal_Servico_Repo_AggregateCustomSe {
    
    public integer GetTempoAtualizacaoCadastral()
    {
        List<TW1_Padroes_relacionamento__c> settings = [
            SELECT 
            TW1_Tempo_Atualizacao_Cadastral__c 
            FROM TW1_Padroes_relacionamento__c];
        if(settings.size() >0)
            return (integer)settings[0].TW1_Tempo_Atualizacao_Cadastral__c;
        else
            return 160;
    }
    
    public string GetUtlApiUAU()
    {
        List<TW1_Custom_Settings__c> settings = [
            SELECT 
            TW1_URLBaseServicoUau__c 
            FROM TW1_Custom_Settings__c];
        if(settings.size() >0)
            return (string)settings[0].TW1_URLBaseServicoUau__c;
        else
            return null;
    }
    
    public string GetUrlApiAssitenciaTecnica()
    {
        List<TW1_Custom_Settings__c> settings = [
            SELECT 
            TW1_URLBaseServicoAT__c 
            FROM TW1_Custom_Settings__c];
        if(settings.size() >0)
            return (string)settings[0].TW1_URLBaseServicoAT__c;
        else
            return null;
    }
    
    public string GetURLCallBackAT()
    {
        //URLCallBackAT
        List<TW1_Custom_Settings__c> settings = [
            SELECT 
            TW1_URLCallBackAT__c 
            FROM TW1_Custom_Settings__c];
        if(settings.size() >0)
            return (string)settings[0].TW1_URLCallBackAT__c;
        else
            return null;
    }
    
    public string GetParcelaNaoConciliadaInadimplencia()
    {
        List<TW1_Padroes_Inadimplencia__c> settings =  [SELECT 
                                                        TW1_parcelaNaoConciliada__c 
                                                        FROM TW1_Padroes_Inadimplencia__c];
        if(settings.size() >0)
            return string.valueOf(settings[0].TW1_parcelaNaoConciliada__c);
        else
            return null; 
    }
    
    public string GetQtdDiasVencimentoInadimplencia()
    {
        List<TW1_Padroes_Inadimplencia__c> settings =  [SELECT 
                                                        TW1_qtdDiasVencimento__c 
                                                        FROM TW1_Padroes_Inadimplencia__c];
        if(settings.size() > 0)
            return string.valueOf(settings[0].TW1_qtdDiasVencimento__c);
        else
            return null; 
    }
    
    public string GetUrlCallbackInadimplencia()
    { 
        List<TW1_Padroes_Inadimplencia__c> settings =  [SELECT 
                                                        TW1_urlCallback__c 
                                                        FROM TW1_Padroes_Inadimplencia__c];
        if(settings.size() > 0)
            return string.valueOf(settings[0].TW1_urlCallback__c);
        else
            return null;     	
    }
    
    public string GetCallBackAtualizacaoCadastralUAU()
    { 
        List<TW1_Custom_Settings__c> settings =  [SELECT 
                                                  TW1_URLCallBackAtualizacaoCadastralUAU__c 
                                                  FROM TW1_Custom_Settings__c];
        if(settings.size() > 0)
            return string.valueOf(settings[0].TW1_URLCallBackAtualizacaoCadastralUAU__c);
        else
            return null;     	
    }
    
    public string GetLoginAuthUAU()
    { 
        List<TW1_Custom_Settings__c> settings =  [SELECT 
                                                  TW1_LoginUau__c  
                                                  FROM TW1_Custom_Settings__c];
        if(settings.size() > 0)
            return string.valueOf(settings[0].TW1_LoginUau__c);
        else
            return null;     	
    }
    
    public string GetSenhaAuthUAU()
    { 
        List<TW1_Custom_Settings__c> settings =  [SELECT 
                                                  TW1_SenhaUau__c   
                                                  FROM TW1_Custom_Settings__c];
        if(settings.size() > 0)
            return string.valueOf(settings[0].TW1_SenhaUau__c );
        else
            return null;     	
    }
    
     public Boolean GetUsaBaseProducaoAuthUAU()
    { 
        List<TW1_Custom_Settings__c> settings =  [SELECT 
                                                  TW1_BaseProducaoUau__c    
                                                  FROM TW1_Custom_Settings__c];
        if(settings.size() > 0)
            return settings[0].TW1_BaseProducaoUau__c;
        else
            return null;     	
    }
}